### PR TITLE
python game

### PR DESCRIPTION
**Pull request by soujanya-08**

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@soujanya-08 

**Thank you for contributing!**

- Please add your program in Programs/Python folder 

Don't forget to give a ⭐

**Comment by soujanya-08** [comment]
ok👍

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
@soujanya-08 

- You have deleted another file Key_Logger.py
- Please fix this issue

**Review by CODING-Enthusiast9857 — APPROVED** [review]
@soujanya-08 

**Thank you for contributing!**

**Pull request merged**
