### PR TITLE
Prims Algorithm added

### PR DESCRIPTION
**Pull request by vivekkdagar**
Prims Algorithm for graph added.

### CODE REVIEW

**Review by CODING-Enthusiast9857 — CHANGES_REQUESTED** [review]
Hey @vivekkdagar 
Can you please create one **readme.md** file in implementation folder & explain the working of your code there so that viewer can understand it properly.
Thank You.

**Comment by vivekkdagar** [comment]
Definitely.

**Review by vivekkdagar — COMMENTED** [review]
Added readme.md

**Review by CODING-Enthusiast9857 — APPROVED** [review]
Alright

**Pull request merged**
